apiVersion: apps/v1
kind: Deployment
metadata:
  name: livros-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livros-api
  template:
    metadata:
      labels:
        app: livros-api
    spec:
      containers:
        - name: livros-api
          image: ghcr.io/igorsantosd3v/backendproject:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./livros.db"
            - name: MEU_USUARIO
              value: "admin"
            - name: MINHA_SENHA
              value: "admin"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_SERVER
              value: "kafka:9092"