input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => '"timestamp":"%{TIMESTAMP_ISO8601:timestamp}"\s*,\s*"level":"%{WORD:level}"\s*,\s*"logger":"%{DATA:logger}"\s*,\s*"message":"%{GREEDYDATA:log_message}"'
    }
    tag_on_failure => ["_grokparsefailure"]
  }

  json {
    source => "message"
    target => "log_json"
    skip_on_invalid_json => true
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    timezone => "UTC"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "livros-logs"
  }

  stdout {
    codec => rubydebug
  }
}